### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by xMacoy01** [Doc-SLAV/catsgang#4]
Traceback (most recent call last):
  File "C:\Users\x\Desktop\CatsGangBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\x\Desktop\CatsGangBot-main\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\x\Desktop\CatsGangBot-main\bot\utils\launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "C:\Users\x\Desktop\CatsGangBot-main\bot\core\tapper.py", line 23, in <module>
    from httpx import HTTPStatusError
ModuleNotFoundError: No module named 'httpx'
Restarting the program in 10 seconds...

**Comment by Doc-SLAV** [comment]
pip3 install httpx
